#!/usr/bin/env python3
"""生成一个约 6000 行、80 节的大文档 big.tex，用来测性能：高亮、大纲、滚动、SyncTeX、补全扫描。"""
import random, os

random.seed(42)
words = ("lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor "
         "incididunt ut labore et dolore magna aliqua quis nostrud exercitation ullamco").split()

def para(n):
    return " ".join(random.choice(words) for _ in range(n)) + "."

out = []
out.append(r"""\documentclass{article}
\usepackage{amsmath}
\usepackage{hyperref}
\title{Large document (generated by generate.py)}
\begin{document}
\maketitle
\tableofcontents
""")
for s in range(1, 81):
    out.append(f"\\section{{Section {s}}}\\label{{sec:{s}}}")
    for ss in range(1, 4):
        out.append(f"\\subsection{{Subsection {s}.{ss}}}\\label{{sec:{s}-{ss}}}")
        for p in range(4):
            out.append(para(random.randint(40, 70)))
            out.append("")
        out.append("\\begin{equation}\\label{eq:%d-%d}" % (s, ss))
        out.append("  \\sum_{i=1}^{n} x_i^{%d} = \\int_0^1 f_{%d}(t)\\,\\mathrm{d}t" % (ss, s))
        out.append("\\end{equation}")
        out.append("Inline math $a_{%d} + b_{%d} = c$ and a reference to Equation~\\eqref{eq:%d-%d}." % (s, ss, s, ss))
        out.append("%% comment line %d.%d with a $ sign that must not start math" % (s, ss))
        out.append("")
        out.append("\\begin{itemize}")
        for it in range(3):
            out.append("  \\item %s" % para(12))
        out.append("\\end{itemize}")
        out.append("")
out.append(r"\end{document}")

path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "big.tex")
with open(path, "w") as f:
    f.write("\n".join(out) + "\n")
print("wrote", path, sum(1 for _ in open(path)), "lines")
